### ISSUE TITLE
cloneができていない

### ISSUE THREAD

**Issue by kankanSunaga** [KantaSunaga/goss#1]
Commands/create.go
の
```
func clone(endpoint string){
	 fs := memfs.New()
	 storer := memory.NewStorage()
	 _, err := git.Clone(storer, fs, &git.CloneOptions{
		 URL: endpoint,
	 })
	 if err != nil {
	 	fmt.Println("エラーだよ")
	 	log.Fatal(err)
	 }
	 changelog, err := fs.Open("CHANGELOG")
	 if err != nil {
		 fmt.Println("エラーだよ1")
		 log.Fatal(err)
	 }

	 io.Copy(os.Stdout, changelog)
 }
```

 _, err := git.Clone(storer, fs, &git.CloneOptions{
		 URL: endpoint,
	 })

この箇所でエラーは発生していないものの、
うまくcloneができていません。
おそらく
` storer := memory.NewStorage()` 
ここでパスが指定できていないからだとおもうのですが、
解決方法がわかりません・・・
よろしくお願いします

**Comment by d-kuro** [comment]
```
memory.NewStorage()
```

多分これだとインメモリに clone する、みたいな感じになってるんじゃないかなと思います！
このサンプル通りにディレクトリを指定する感じにしてみると動くような気がしています！
https://github.com/src-d/go-git/blob/master/_examples/clone/main.go
