### ISSUE TITLE
外部ライブラリの構造体にたいしてレシーバメソッドを追加したいが、うまくできない

### ISSUE THREAD

**Issue by kankanSunaga** [KantaSunaga/goss#4]
https://github.com/KantaSunaga/goss/blob/feature/clone/Commands/create.go#L28
の戻り値といて返された構造体に、

https://github.com/KantaSunaga/goss/blob/feature/clone/Commands/create.go#L56
↑をレシーバメソッドとして実行したいのですが、外部ライブラリの構造体を認識してくれません。

そうやるのが良いでしょうか？

**Comment by d-kuro** [comment]
これは仕様上できないという認識です。
その場合は一度

```go
type Foo struct {
	 repo git.Repository
}

func (f *Foo) Push() error {}
```

 みたいに自前の type を経由してあげる必要があります

**Comment by KantaSunaga** [comment]
ちなみにこれは設計ミスである可能性が高い時にやる行為ですか？
それとも割と普通にしますか？
